name: Daily Expense API NestJS CI

on:
  push:
    branches:
      - develop
      - main

    pull_request:
      branches:
        - develop
        - main

  jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [24]

      steps:
        - uses: action/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: npm

        - run: npm ci

        - run: npm run init

        - run: npm test

        - run: npm run build
